# These are supported funding model platforms

github: # ma-9
patreon: # Manavoza7
open_collective: # Manavoza7
ko_fi: # Manavoza7
community_bridge: # [Marvellous-In](https://marvellous-india.herokuapp.com/)
liberapay: # Manavoza7
issuehunt: # Manavoza7
otechie: # Manavoza7
custom: # ['https://manavoza.com','https://marvellous-india.herokuapp.com/']
